apiVersion: v1
kind: Service
metadata:
  name: tcp-server
  #namespace: tcp-server
spec:
  ports:
  - port: 8888
    targetPort: 8888
    name: tcp # adding for Istio
  selector:
    app: "tcp-server"
  type: ClusterIP